### PR TITLE
Support custom openai compatible endpoints

### PR DESCRIPTION
**Pull request by raldone01**
Fixes: #16
Includes: #17

Adds German translations.
Should the `UNIQUE_ID` generation change for example when openai introduces a way to automatically discover all voices old entries should not be affected.
I put in a workaround for upgrades from old versions. Please test that old entries still work.

I can generate audio using openai and `openedai-speech`.
Both can be configured at the same time.

### CODE REVIEW

**Review by sfortis — APPROVED** [review]

**Comment by sfortis** [comment]
thanks @raldone01 , i dont have a local endpoint to test but seems good!

**Comment by raldone01** [comment]
@sfortis would you be interested in a pull request to also add stt support?

**Comment by qJake** [comment]
Yes! Thanks @sfortis - gonna try this out right now. Hoping that I can ditch my hacked custom component and just stick with this one!

**Comment by qJake** [comment]
Oh no it doesn't work! 😥 I'll open a bug for it.

**Comment by sfortis** [comment]
@raldone01 actually i'm working (locally) on a STT component that is almost ready (works perfectly from android app, watch, esp32box3, still needs some work on optionflow). Since i want them separate, i'll create a new repo. What about working together on this?

**Comment by sfortis** [comment]
@qJake great! i'll drop a new release soon! did you spot any issues updating from the existing 2.3 on existing integrations?

**Comment by raldone01** [comment]
@sfortis good that I asked then.
I can help you if you get stuck anywhere.

My plan was to just add a step to the config flow where one selects if a tts or stt device should be added.
Any reason why you want two integrations?
Quite a bit of code could be shared I think.
(If you really want two that's fine too.)

Have you thought about upstreaming the integration to core sometime in the future?
Core is currently working hard on assistants and they might be interested.

I would have used https://github.com/shiipou/openai_stt as the base.

**Comment by qJake** [comment]
> @qJake great! i'll drop a new release soon! did you spot any issues updating from the existing 2.3 on existing integrations?
> 
> I want to also merge a sound processing function using ffmpeg, to normalize, compress, and equalize the response audio so it is better audible on small speakers, like those in watches and esp32 devices. This will be parametrized in config flow/option flow.

I don't use the standard OpenAI TTS so I can't say, but so far all of my automations and TTS-related services appear to be fine!

**Comment by defaultsecurity** [comment]
@sfortis 
Where can we configure the custom openai endpoint url?

I would like to use:
https://github.com/matatonic/openedai-speech

**Comment by defaultsecurity** [comment]
> @sfortis Where can we configure the custom openai endpoint url?
> 
> I would like to use: https://github.com/matatonic/openedai-speech

Sorry, my bad. I have confused this integration with the OpenAI Conversation integration. Everything seems to be in order. Thank you for your work.

**Pull request merged**
